### ISSUE TITLE
misnaming of agents in Crew

### ISSUE THREAD

**Issue by iplayfast** [yanniedog/crewai-autocrew#12]
```
crew = Crew(
    agents=[PM, AIExpert, Cpp_Developer, QATester, ProductOwner],
    tasks=[task_PM, task_AI_Expert, task_Cpp_Developer, task_QA_Tester, task_Product_Owner],
    verbose=True,
    process=Process.sequential,
)```
should have been
```crew = Crew(
    agents=[PM, AI_Expert, Cpp_Developer, QA_Tester, ProductOwner],
    tasks=[task_PM, task_AI_Expert, task_Cpp_Developer, task_QA_Tester, task_Product_Owner],
    verbose=True,
    process=Process.sequential,
)
```

**Comment by yanniedog** [comment]
Could you give me more context? Do you get an error? Does CrewAI misinterpret the name of the agent?

**Comment by iplayfast** [comment]
Sorry, I should have given better context. My prompt was something like create a chess game in c++ and the crew had names generated  that were not matched when the task was created. So for instance QATester was originally created as QA_Tester.

**Comment by yanniedog** [comment]
Thank you, yes I know where the problem is. I'll fix this

**Comment by iplayfast** [comment]
fixed
