### ISSUE TITLE
Structuring CrewAI scripts to use the OpenAI api

### ISSUE THREAD

**Issue by yanniedog** [yanniedog/crewai-autocrew#26]
If anyone knows how to use the OpenAI api within a CrewAI script, please let me know, so I can ensure Autocrew generates scripts with the required structure

**Comment by iplayfast** [comment]
Line 25, 
'''from openai import OpenAI'''

should be just 
'''import openai'''

**Comment by yanniedog** [comment]
https://app.grit.io/migrations/new/openai

This is most like the best way to do it

**Comment by yanniedog** [comment]
This functionality was added to version 2.1.0
