### ISSUE TITLE
Small formatting errors - too many doublequotes etc.

### ISSUE THREAD

**Issue by PiotrEsse** [yanniedog/crewai-autocrew#3]
Thats ......Awesome.....
One thing thou - issues. It seeme your code generate too much doublequotes. :
![image](https://github.com/yanniedog/crewai-autocrew/assets/42764623/a2180150-d335-4bc6-ba16-b82c479e0d49)

Original crew definition looks different:
![image](https://github.com/yanniedog/crewai-autocrew/assets/42764623/b45bfa8b-e54e-4f64-b8ef-08fe8edacab3)

If I strip doublequotes and make small formatting changes the crewai-script.py sucessfully runs.

**Comment by yanniedog** [comment]
Thanks very much for raising this. It's really clear. Will fix now

**Comment by yanniedog** [comment]
This should be resolved now
